-- remove NO_ZERO_DATE from sql_mode
SELECT @@GLOBAL.sql_mode;
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- add columns to oxvouchers
ALTER TABLE `oxvouchers` ADD `OXAC_BIRTHDAYVOUCHER` DATE DEFAULT '0000-00-00';
ALTER TABLE `oxvouchers` ADD `OXAC_BIRTHDAYVOUCHERUSERID` CHAR(32) DEFAULT NULL;
